name: DupeDetection
version: ${version}
main: notauthorised.dupedetection.DupeDetectionPlugin
api-version: 1.18
description: A universal plugin to detect and prevent item duplication exploits (1.18.2 - 1.21.8+)
author: notauthorised
website: https://github.com/CassidyMabey/dupedetection
authors: [notauthorised]
softdepend: [Vault, PlaceholderAPI]

commands:
  dupedetection:
    description: Main command for DupeDetection
    usage: /dupedetection <reload|info|limits|setlimit|check|exception|help>
    permission: dupedetection.admin
    aliases: [dd, dupedect]

permissions:
  dupedetection.admin:
    description: Admin permissions for DupeDetection
    default: op
  dupedetection.bypass:
    description: Bypass dupe detection checks
    default: false